In [1]:
import tensorflow as tf
import numpy as np

# Create random integer tensors
a = tf.random.uniform(shape=[16, 16], minval=0, maxval=101, dtype=tf.int32)
b = tf.random.uniform(shape=[16, 16], minval=0, maxval=101, dtype=tf.int32)

print("Addition:\n", tf.add(a, b))
print("\nSubtraction:\n", tf.subtract(a, b))
print("\nElement-wise Multiplication:\n", tf.multiply(a, b))
print("\nMatrix Multiplication:\n", tf.matmul(a, b))
print("\nDivision:\n", tf.divide(a, b))
print("\nMean of A:", tf.reduce_mean(a))
print("\nMax of B:", tf.reduce_max(b))
print("\nTranspose of A:\n", tf.transpose(a))

# Broadcasting example (adding identity matrix)
c = tf.eye(num_rows=16, dtype=tf.int32)
print("\nBroadcasted Add:\n", a + c)

# Reshaping and slicing
arr = tf.constant(np.arange(1, 13), shape=(3, 4))
print("\nOriginal:\n", arr)
print("\nSlice [1:3, 1:3]:\n", arr[1:3, 1:3])

# Gradient computation using GradientTape
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x**2 + 5*x + 2
grad = tape.gradient(y, x)
print("\nGradient of y = x² + 5x + 2 at x=3:", grad.numpy())


import torch
import numpy as np

A = torch.randint(low=0, high=101, size=(16, 16))
B = torch.randint(low=0, high=101, size=(16, 16))

# Basic operations
print("Addition:\n", A + B)
print("\nSubtraction:\n", A - B)
print("\nElementwise Multiplication:\n", A * B)
print("\nMatrix Multiplication:\n", torch.mm(A, B))
print("\nDivision:\n", A / B)
print("\nTranspose:\n", A.T)
print("\nMean of A:", A.float().mean())
print("\nMax of B:", B.max())

# Reshape and concatenate
C = torch.arange(1, 13).reshape(3, 4)
print("\nOriginal Tensor C:\n", C)
print("\nReshaped (2,6):\n", C.reshape(2,6))
print("\nConcatenation along rows:\n", torch.cat([A, B], dim=0))

# Automatic differentiation
x = torch.tensor(3.0, requires_grad=True)
y = x**2 + 5*x + 2
y.backward()
print("\nGradient dy/dx at x=3:", x.grad.item())


Addition:
 tf.Tensor(
[[103  55  68 120 121  51 108 142  84 134 145 105  75 197  26  51]
 [119 173 120  63 103  51 154  20 178  66 141  99 113 177  97 180]
 [164  53 107 133 159 134   4  80  21  88 113 156  93  23  79  82]
 [162 105  89  45 105 123  95  99  30 146  94 150 110 118  98  59]
 [ 65  91  83 121  50 123  88 125  52 163 112  89  11 179  45  75]
 [ 92  91  82  70 112  96 138  63  97  73 127 152  92 138  99  88]
 [101 117  57 174 106  59  79  94 143  90 163  46 140 172 170  10]
 [ 30 108  76  99  51  89 121  81 130  76  73 188 118 127 182 132]
 [ 91 158  84 145  45 117  60 168  83 134  85  29  76 122 125  94]
 [129 109  59 121 113 175 169  86  95  86  93 115 100  85 112 123]
 [133  29  42  65 125 109  34  57  89 100 101 134  79 108 197  45]
 [ 75 168 160 133  70 103  71  54  14  70 131 113 114 121 154 139]
 [142  62 129  57 124 107  58  44 130 148 121  56 108 146 124 199]
 [ 95  66 122 161 129 174 173 136  80  90 107  80  81 122 110  34]
 [ 38  54 121 196  46  64 112 141 143 14